package com.findev.fintrack.loanengine

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Test
import java.time.LocalDate

/**
 * Checked against a real signed contract: АО «Яндекс Банк», нецелевой потребительский
 * кредит через СБП, УИД 4e9ebc1d-9eda-11f0-b5d7-2edeaa97852c-7.
 *
 * 99 999,00 ₽ over 24 payments, 01.10.2025 -> 01.10.2027, payment on the 1st. Two rates,
 * both fixed at signing: 70% from 01.10.2025 to 01.05.2026, then 28,572% to 01.10.2027.
 * Payment 6696,00 every month, 6680,32 on the last one. ПСК in the contract: 50,441% /
 * 60 689,32 ₽.
 *
 * The reference figures below are the contract's own printed schedule, not this engine's
 * output. That is the whole point of the file: a schedule generated by the code under
 * test would only prove the code has not changed, never that it is right.
 *
 * Convenient accident worth stating: 2025-2027 contains no leap year, so ACT/ACT and
 * ACT/365 cannot disagree here. This fixture does not exercise the leap-year split.
 */
class ContractPaymentScheduleTest {

    private val contractPaymentMinor = 6696_00L

    private val loan = Loan(
        type = LoanType.ANNUITY,
        principalMinor = 99_999_00,
        annualRateMilliPercent = 70000,
        startDate = LocalDate.of(2025, 10, 1),
        termMonths = 24,
        paymentDay = 1,
        fixedPaymentMinor = contractPaymentMinor,
    )

    /**
     * The contract dates the switch "с 02.05.2026", but its own schedule charges the whole
     * 01.05 -> 01.06 period at the lower rate, so accrual-wise it takes effect on 01.05.
     *
     * 28,572% is why rates are stored in thousandths of a percent. In basis points it
     * truncates to 2857, and that alone put the final payment 1,86 ₽ out.
     */
    private val rateChanges = listOf(RateChange(LocalDate.of(2026, 5, 1), 28572))

    /**
     * Rows the engine puts exactly one kopeck above the contract.
     *
     * Investigated rather than waved away. The bank is not simply truncating: truncation
     * reproduces 3 of the 8 printed rows, HALF_UP reproduces 6. What fits is that the bank
     * carries an unrounded balance internally and rounds only for print, which cannot be
     * reconstructed from a printed schedule. HALF_UP stays - it is the project's rule and
     * the better fit of the two.
     *
     * These two kopecks are the only divergence in the whole contract, and they are also
     * the entire explanation for the final payment: two kopecks of interest not taken is
     * two kopecks of principal left over, which the last payment clears.
     */
    private val knownKopeckHighRows = setOf(2, 5)

    @Test
    fun openingPaymentComesFromTheContractNotTheFormula() {
        // The gap this feature exists to close: the formula's answer is 1149,53 out.
        val formulaPayment = annuityPaymentMinor(99_999_00, 70000, 24)
        assertEquals(7845_53L, formulaPayment)
        assertNotEquals(formulaPayment, contractPaymentMinor)

        val schedule = generateSchedule(loan, rateChanges)
        assertEquals(contractPaymentMinor, schedule.first().paymentMinor)
    }

    @Test
    fun paymentStaysLevelAcrossTheRateChange() {
        val schedule = generateSchedule(loan, rateChanges)

        // Every payment but the last is the contract's 6696,00 - including payment 8,
        // the first one priced at the lower rate.
        schedule.dropLast(1).forEach { entry ->
            assertEquals("payment ${entry.number}", contractPaymentMinor, entry.paymentMinor)
        }
    }

    @Test
    fun interestMatchesTheContractsPrintedSchedule() {
        val schedule = generateSchedule(loan, rateChanges)

        // Contract rows 1..8. Row 8 is the first at 28,572%, and the drop from 5404,81 to
        // 2248,29 is the rate change landing.
        val expected = listOf(
            1 to 5945_15L,
            2 to 5710_16L,
            3 to 5841_90L,
            4 to 5791_12L,
            5 to 5182_09L,
            6 to 5647_32L,
            7 to 5404_81L,
            8 to 2248_29L,
        )
        // Collected, not asserted row by row: a per-row assert stops at the first mismatch
        // and hides how many others were fine. Each row is pinned to its exact expected
        // offset, so a drift in either direction fails - including a row silently becoming
        // correct, which would mean the rounding story changed and this file is stale.
        val offsets = expected.associate { (number, interestMinor) ->
            number to (schedule[number - 1].interestMinor - interestMinor)
        }
        val wanted = expected.associate { (number, _) ->
            number to if (number in knownKopeckHighRows) 1L else 0L
        }
        assertEquals(wanted, offsets)
    }

    @Test
    fun lastPaymentAndTotalsMatchTheContract() {
        val schedule = generateSchedule(loan, rateChanges)

        assertEquals(24, schedule.size)
        assertEquals(0L, schedule.last().balanceAfterMinor)

        // The principal is the one total that has to be exact: it is the money borrowed,
        // not a derived figure, so no rounding may leak into it.
        assertEquals(99_999_00L, schedule.sumOf { it.principalMinor })

        // "Итого: 160688.32  60689.32  99999.00", plus the two kopecks from rows 2 and 5.
        val kopecksOver = knownKopeckHighRows.size.toLong()
        assertEquals(60_689_32L + kopecksOver, schedule.sumOf { it.interestMinor })
        assertEquals(160_688_32L + kopecksOver, schedule.sumOf { it.paymentMinor })
        assertEquals(6680_32L + kopecksOver, schedule.last().paymentMinor)
    }

    @Test
    fun withoutTheContractPaymentTheScheduleDivergesFromTheContract() {
        // Guards the reason this flag exists: re-annuitising is right for a rate that
        // moves unexpectedly, and wrong for one whose steps were priced in at signing.
        val derived = generateSchedule(loan.copy(fixedPaymentMinor = null), rateChanges)

        assertNotEquals(contractPaymentMinor, derived.first().paymentMinor)
        assertNotEquals(60_689_32L, derived.sumOf { it.interestMinor })
    }
}
